name: Docker CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to Github registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Get version
      run: grep -m 1 version pyproject.toml | cut --delimiter="=" -f2 | cut -d '"' -f 2
      id: get_version
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64,linux/arm/v7,linux/arm64
        context: .
        file: Dockerfile
        push: true
        tags: ghcr.io/niwla23/mqtt-phone-siren:latest,ghcr.io/niwla23/mqtt-phone-siren:${{steps.get_version.outputs.version}}